# Generated by Django 3.0.3 on 2020-02-18 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase', models.DecimalField(decimal_places=2, max_digits=5)),
                ('selling', models.DecimalField(decimal_places=2, max_digits=5)),
                ('from_data', models.DateField()),
                ('until_data', models.DateField(blank=True, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_history', to='model.Currency')),
            ],
            options={
                'unique_together': {('currency', 'from_data')},
            },
        ),
    ]
