# Generated by Django 3.0.3 on 2020-02-24 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_auto_20200221_1225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangehistory',
            options={'ordering': ['from_date']},
        ),
        migrations.AlterUniqueTogether(
            name='exchangehistory',
            unique_together=set(),
        ),
    ]
